// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: bilge/lahmacun/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgUpdateParams is the Msg/UpdateParams request type.
type MsgUpdateParams struct {
	// authority is the address that controls the module (defaults to x/gov unless overwritten).
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	// params defines the module parameters to update.
	//
	// NOTE: All parameters must be supplied.
	Params Params `protobuf:"bytes,2,opt,name=params,proto3" json:"params"`
}

func (m *MsgUpdateParams) Reset()         { *m = MsgUpdateParams{} }
func (m *MsgUpdateParams) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateParams) ProtoMessage()    {}
func (*MsgUpdateParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_bfa42cbdad4a2ed7, []int{0}
}
func (m *MsgUpdateParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateParams.Merge(m, src)
}
func (m *MsgUpdateParams) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateParams) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateParams.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateParams proto.InternalMessageInfo

func (m *MsgUpdateParams) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgUpdateParams) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

// MsgUpdateParamsResponse defines the response structure for executing a
// MsgUpdateParams message.
type MsgUpdateParamsResponse struct {
}

func (m *MsgUpdateParamsResponse) Reset()         { *m = MsgUpdateParamsResponse{} }
func (m *MsgUpdateParamsResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateParamsResponse) ProtoMessage()    {}
func (*MsgUpdateParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bfa42cbdad4a2ed7, []int{1}
}
func (m *MsgUpdateParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateParamsResponse.Merge(m, src)
}
func (m *MsgUpdateParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateParamsResponse proto.InternalMessageInfo

// MsgCreateLahmacun defines a message for creating a Lahmacun.
type MsgCreateLahmacun struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Id      string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty" yaml:"id"`
	Heat    string `protobuf:"bytes,3,opt,name=heat,proto3" json:"heat,omitempty" yaml:"heat"`
	Dough   string `protobuf:"bytes,4,opt,name=dough,proto3" json:"dough,omitempty" yaml:"dough"`
	Meat    string `protobuf:"bytes,5,opt,name=meat,proto3" json:"meat,omitempty" yaml:"meat"`
	Tomato  string `protobuf:"bytes,6,opt,name=tomato,proto3" json:"tomato,omitempty" yaml:"tomato"`
	Onion   string `protobuf:"bytes,7,opt,name=onion,proto3" json:"onion,omitempty" yaml:"onion"`
}

func (m *MsgCreateLahmacun) Reset()         { *m = MsgCreateLahmacun{} }
func (m *MsgCreateLahmacun) String() string { return proto.CompactTextString(m) }
func (*MsgCreateLahmacun) ProtoMessage()    {}
func (*MsgCreateLahmacun) Descriptor() ([]byte, []int) {
	return fileDescriptor_bfa42cbdad4a2ed7, []int{2}
}
func (m *MsgCreateLahmacun) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateLahmacun) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateLahmacun.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateLahmacun) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateLahmacun.Merge(m, src)
}
func (m *MsgCreateLahmacun) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateLahmacun) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateLahmacun.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateLahmacun proto.InternalMessageInfo

func (m *MsgCreateLahmacun) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgCreateLahmacun) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MsgCreateLahmacun) GetHeat() string {
	if m != nil {
		return m.Heat
	}
	return ""
}

func (m *MsgCreateLahmacun) GetDough() string {
	if m != nil {
		return m.Dough
	}
	return ""
}

func (m *MsgCreateLahmacun) GetMeat() string {
	if m != nil {
		return m.Meat
	}
	return ""
}

func (m *MsgCreateLahmacun) GetTomato() string {
	if m != nil {
		return m.Tomato
	}
	return ""
}

func (m *MsgCreateLahmacun) GetOnion() string {
	if m != nil {
		return m.Onion
	}
	return ""
}

// MsgCreateLahmacunResponse defines the response for creating a Lahmacun.
type MsgCreateLahmacunResponse struct {
}

func (m *MsgCreateLahmacunResponse) Reset()         { *m = MsgCreateLahmacunResponse{} }
func (m *MsgCreateLahmacunResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCreateLahmacunResponse) ProtoMessage()    {}
func (*MsgCreateLahmacunResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bfa42cbdad4a2ed7, []int{3}
}
func (m *MsgCreateLahmacunResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateLahmacunResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateLahmacunResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateLahmacunResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateLahmacunResponse.Merge(m, src)
}
func (m *MsgCreateLahmacunResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateLahmacunResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateLahmacunResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateLahmacunResponse proto.InternalMessageInfo

// MsgUpdateLahmacun defines a message for updating a Lahmacun.
type MsgUpdateLahmacun struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Id      string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty" yaml:"id"`
	Heat    string `protobuf:"bytes,3,opt,name=heat,proto3" json:"heat,omitempty" yaml:"heat"`
	Dough   string `protobuf:"bytes,4,opt,name=dough,proto3" json:"dough,omitempty" yaml:"dough"`
	Meat    string `protobuf:"bytes,5,opt,name=meat,proto3" json:"meat,omitempty" yaml:"meat"`
	Tomato  string `protobuf:"bytes,6,opt,name=tomato,proto3" json:"tomato,omitempty" yaml:"tomato"`
	Onion   string `protobuf:"bytes,7,opt,name=onion,proto3" json:"onion,omitempty" yaml:"onion"`
}

func (m *MsgUpdateLahmacun) Reset()         { *m = MsgUpdateLahmacun{} }
func (m *MsgUpdateLahmacun) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateLahmacun) ProtoMessage()    {}
func (*MsgUpdateLahmacun) Descriptor() ([]byte, []int) {
	return fileDescriptor_bfa42cbdad4a2ed7, []int{4}
}
func (m *MsgUpdateLahmacun) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateLahmacun) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateLahmacun.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateLahmacun) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateLahmacun.Merge(m, src)
}
func (m *MsgUpdateLahmacun) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateLahmacun) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateLahmacun.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateLahmacun proto.InternalMessageInfo

func (m *MsgUpdateLahmacun) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgUpdateLahmacun) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MsgUpdateLahmacun) GetHeat() string {
	if m != nil {
		return m.Heat
	}
	return ""
}

func (m *MsgUpdateLahmacun) GetDough() string {
	if m != nil {
		return m.Dough
	}
	return ""
}

func (m *MsgUpdateLahmacun) GetMeat() string {
	if m != nil {
		return m.Meat
	}
	return ""
}

func (m *MsgUpdateLahmacun) GetTomato() string {
	if m != nil {
		return m.Tomato
	}
	return ""
}

func (m *MsgUpdateLahmacun) GetOnion() string {
	if m != nil {
		return m.Onion
	}
	return ""
}

// MsgUpdateLahmacunResponse defines the response for updating a Lahmacun.
type MsgUpdateLahmacunResponse struct {
}

func (m *MsgUpdateLahmacunResponse) Reset()         { *m = MsgUpdateLahmacunResponse{} }
func (m *MsgUpdateLahmacunResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateLahmacunResponse) ProtoMessage()    {}
func (*MsgUpdateLahmacunResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bfa42cbdad4a2ed7, []int{5}
}
func (m *MsgUpdateLahmacunResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateLahmacunResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateLahmacunResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateLahmacunResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateLahmacunResponse.Merge(m, src)
}
func (m *MsgUpdateLahmacunResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateLahmacunResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateLahmacunResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateLahmacunResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgUpdateParams)(nil), "bilge.lahmacun.MsgUpdateParams")
	proto.RegisterType((*MsgUpdateParamsResponse)(nil), "bilge.lahmacun.MsgUpdateParamsResponse")
	proto.RegisterType((*MsgCreateLahmacun)(nil), "bilge.lahmacun.MsgCreateLahmacun")
	proto.RegisterType((*MsgCreateLahmacunResponse)(nil), "bilge.lahmacun.MsgCreateLahmacunResponse")
	proto.RegisterType((*MsgUpdateLahmacun)(nil), "bilge.lahmacun.MsgUpdateLahmacun")
	proto.RegisterType((*MsgUpdateLahmacunResponse)(nil), "bilge.lahmacun.MsgUpdateLahmacunResponse")
}

func init() { proto.RegisterFile("bilge/lahmacun/tx.proto", fileDescriptor_bfa42cbdad4a2ed7) }

var fileDescriptor_bfa42cbdad4a2ed7 = []byte{
	// 548 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x54, 0x4f, 0x6b, 0x13, 0x41,
	0x1c, 0xcd, 0xa6, 0x4d, 0x4a, 0xa6, 0x69, 0x6b, 0x86, 0xd2, 0x6c, 0x52, 0xba, 0x9b, 0x8e, 0xa0,
	0x6d, 0xc0, 0xac, 0xa6, 0x20, 0x98, 0x9b, 0xf1, 0x6a, 0x40, 0x56, 0x04, 0xf1, 0xa0, 0x4c, 0xb3,
	0xcb, 0x66, 0x21, 0xbb, 0xb3, 0xec, 0x4c, 0xa4, 0xb9, 0x89, 0x47, 0x4f, 0x7e, 0x0a, 0xf1, 0x98,
	0x83, 0x97, 0x7e, 0x83, 0x1e, 0x8b, 0x27, 0x4f, 0x8b, 0x24, 0x87, 0xdc, 0xf3, 0x09, 0x64, 0x66,
	0x76, 0x89, 0x99, 0x56, 0x03, 0x9e, 0xbd, 0xec, 0x9f, 0xf7, 0xde, 0xef, 0xfd, 0x7e, 0xf3, 0x98,
	0x19, 0x50, 0x3d, 0xf7, 0x87, 0x9e, 0x6b, 0x0d, 0xf1, 0x20, 0xc0, 0xfd, 0x51, 0x68, 0xb1, 0x8b,
	0x56, 0x14, 0x13, 0x46, 0xe0, 0xae, 0x20, 0x5a, 0x19, 0x51, 0xaf, 0xe0, 0xc0, 0x0f, 0x89, 0x25,
	0x9e, 0x52, 0x52, 0xaf, 0xf6, 0x09, 0x0d, 0x08, 0xb5, 0x02, 0xea, 0x59, 0xef, 0x1f, 0xf1, 0x57,
	0x4a, 0xd4, 0x24, 0xf1, 0x4e, 0xfc, 0x59, 0xf2, 0x27, 0xa5, 0xf6, 0x3d, 0xe2, 0x11, 0x89, 0xf3,
	0xaf, 0x14, 0x3d, 0x54, 0xa6, 0x88, 0x70, 0x8c, 0x83, 0xac, 0xe4, 0x48, 0x21, 0xb3, 0x0f, 0x49,
	0xa3, 0x4b, 0x0d, 0xec, 0xf5, 0xa8, 0xf7, 0x2a, 0x72, 0x30, 0x73, 0x5f, 0x88, 0x42, 0xf8, 0x18,
	0x94, 0xf0, 0x88, 0x0d, 0x48, 0xec, 0xb3, 0xb1, 0xae, 0x35, 0xb4, 0x93, 0x52, 0x57, 0xff, 0xfe,
	0xed, 0xc1, 0x7e, 0x3a, 0xca, 0x53, 0xc7, 0x89, 0x5d, 0x4a, 0x5f, 0xb2, 0xd8, 0x0f, 0x3d, 0x7b,
	0x29, 0x85, 0x4f, 0x40, 0x51, 0xb6, 0xd6, 0xf3, 0x0d, 0xed, 0x64, 0xbb, 0x7d, 0xd0, 0x5a, 0x4d,
	0xa1, 0x25, 0xfd, 0xbb, 0xa5, 0xab, 0xc4, 0xcc, 0x7d, 0x9d, 0x4f, 0x9a, 0x9a, 0x9d, 0x16, 0x74,
	0xce, 0x3e, 0xce, 0x27, 0xcd, 0xa5, 0xd5, 0xa7, 0xf9, 0xa4, 0xd9, 0x90, 0x83, 0x5f, 0x2c, 0x47,
	0x57, 0xe6, 0x44, 0x35, 0x50, 0x55, 0x20, 0xdb, 0xa5, 0x11, 0x09, 0xa9, 0x8b, 0x2e, 0xf3, 0xa0,
	0xd2, 0xa3, 0xde, 0xb3, 0xd8, 0xc5, 0xcc, 0x7d, 0x9e, 0x1a, 0xc0, 0x36, 0xd8, 0xea, 0x73, 0x84,
	0xc4, 0x6b, 0x97, 0x95, 0x09, 0xe1, 0x11, 0xc8, 0xfb, 0x8e, 0x58, 0x50, 0xa9, 0xbb, 0xb3, 0x48,
	0xcc, 0xd2, 0x18, 0x07, 0xc3, 0x0e, 0xf2, 0x1d, 0x64, 0xe7, 0x7d, 0x07, 0xde, 0x05, 0x9b, 0x03,
	0x17, 0x33, 0x7d, 0x43, 0x08, 0xf6, 0x16, 0x89, 0xb9, 0x2d, 0x05, 0x1c, 0x45, 0xb6, 0x20, 0xe1,
	0x3d, 0x50, 0x70, 0xc8, 0xc8, 0x1b, 0xe8, 0x9b, 0x42, 0x75, 0x67, 0x91, 0x98, 0x65, 0xa9, 0x12,
	0x30, 0xb2, 0x25, 0xcd, 0xcd, 0x02, 0x6e, 0x56, 0x50, 0xcd, 0x02, 0x69, 0xc6, 0x5f, 0xf0, 0x14,
	0x14, 0x19, 0x09, 0x30, 0x23, 0x7a, 0x51, 0xc8, 0x2a, 0x8b, 0xc4, 0xdc, 0x91, 0x32, 0x89, 0x23,
	0x3b, 0x15, 0xf0, 0xbe, 0x24, 0xf4, 0x49, 0xa8, 0x6f, 0xa9, 0x7d, 0x05, 0x8c, 0x6c, 0x49, 0x77,
	0xca, 0x3c, 0xfd, 0x6c, 0xc5, 0xe8, 0x10, 0xd4, 0x6e, 0x44, 0xa7, 0x06, 0x2b, 0x43, 0xff, 0x1f,
	0xec, 0x3f, 0x04, 0xbb, 0x1a, 0x5d, 0x16, 0x6c, 0xfb, 0x4b, 0x1e, 0x6c, 0xf4, 0xa8, 0x07, 0x5f,
	0x83, 0xf2, 0xca, 0x61, 0x34, 0xd5, 0x43, 0xa4, 0x6c, 0xf9, 0xfa, 0xfd, 0x35, 0x82, 0xac, 0x03,
	0x7c, 0x0b, 0x76, 0x95, 0xf3, 0x70, 0x7c, 0x4b, 0xe9, 0xaa, 0xa4, 0x7e, 0xba, 0x56, 0xf2, 0xbb,
	0xbf, 0xb2, 0x2d, 0x8e, 0xff, 0x38, 0xda, 0x5f, 0xfd, 0x6f, 0x4f, 0xa8, 0x5e, 0xf8, 0xc0, 0xaf,
	0x8c, 0xee, 0xc3, 0xab, 0xa9, 0xa1, 0x5d, 0x4f, 0x0d, 0xed, 0xe7, 0xd4, 0xd0, 0x3e, 0xcf, 0x8c,
	0xdc, 0xf5, 0xcc, 0xc8, 0xfd, 0x98, 0x19, 0xb9, 0x37, 0x07, 0x37, 0x6e, 0x0c, 0x36, 0x8e, 0x5c,
	0x7a, 0x5e, 0x14, 0x57, 0xdd, 0xd9, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x1a, 0x65, 0x14, 0xea,
	0xae, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// UpdateParams defines a (governance) operation for updating the module
	// parameters. The authority defaults to the x/gov module account.
	UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error)
	CreateLahmacun(ctx context.Context, in *MsgCreateLahmacun, opts ...grpc.CallOption) (*MsgCreateLahmacunResponse, error)
	UpdateLahmacun(ctx context.Context, in *MsgUpdateLahmacun, opts ...grpc.CallOption) (*MsgUpdateLahmacunResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error) {
	out := new(MsgUpdateParamsResponse)
	err := c.cc.Invoke(ctx, "/bilge.lahmacun.Msg/UpdateParams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) CreateLahmacun(ctx context.Context, in *MsgCreateLahmacun, opts ...grpc.CallOption) (*MsgCreateLahmacunResponse, error) {
	out := new(MsgCreateLahmacunResponse)
	err := c.cc.Invoke(ctx, "/bilge.lahmacun.Msg/CreateLahmacun", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateLahmacun(ctx context.Context, in *MsgUpdateLahmacun, opts ...grpc.CallOption) (*MsgUpdateLahmacunResponse, error) {
	out := new(MsgUpdateLahmacunResponse)
	err := c.cc.Invoke(ctx, "/bilge.lahmacun.Msg/UpdateLahmacun", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// UpdateParams defines a (governance) operation for updating the module
	// parameters. The authority defaults to the x/gov module account.
	UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error)
	CreateLahmacun(context.Context, *MsgCreateLahmacun) (*MsgCreateLahmacunResponse, error)
	UpdateLahmacun(context.Context, *MsgUpdateLahmacun) (*MsgUpdateLahmacunResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) UpdateParams(ctx context.Context, req *MsgUpdateParams) (*MsgUpdateParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateParams not implemented")
}
func (*UnimplementedMsgServer) CreateLahmacun(ctx context.Context, req *MsgCreateLahmacun) (*MsgCreateLahmacunResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateLahmacun not implemented")
}
func (*UnimplementedMsgServer) UpdateLahmacun(ctx context.Context, req *MsgUpdateLahmacun) (*MsgUpdateLahmacunResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateLahmacun not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_UpdateParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bilge.lahmacun.Msg/UpdateParams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateParams(ctx, req.(*MsgUpdateParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_CreateLahmacun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateLahmacun)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateLahmacun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bilge.lahmacun.Msg/CreateLahmacun",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateLahmacun(ctx, req.(*MsgCreateLahmacun))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateLahmacun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateLahmacun)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateLahmacun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bilge.lahmacun.Msg/UpdateLahmacun",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateLahmacun(ctx, req.(*MsgUpdateLahmacun))
	}
	return interceptor(ctx, in, info, handler)
}

var Msg_serviceDesc = _Msg_serviceDesc
var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bilge.lahmacun.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateParams",
			Handler:    _Msg_UpdateParams_Handler,
		},
		{
			MethodName: "CreateLahmacun",
			Handler:    _Msg_CreateLahmacun_Handler,
		},
		{
			MethodName: "UpdateLahmacun",
			Handler:    _Msg_UpdateLahmacun_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bilge/lahmacun/tx.proto",
}

func (m *MsgUpdateParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgCreateLahmacun) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateLahmacun) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateLahmacun) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Onion) > 0 {
		i -= len(m.Onion)
		copy(dAtA[i:], m.Onion)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Onion)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.Tomato) > 0 {
		i -= len(m.Tomato)
		copy(dAtA[i:], m.Tomato)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Tomato)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Meat) > 0 {
		i -= len(m.Meat)
		copy(dAtA[i:], m.Meat)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Meat)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Dough) > 0 {
		i -= len(m.Dough)
		copy(dAtA[i:], m.Dough)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Dough)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Heat) > 0 {
		i -= len(m.Heat)
		copy(dAtA[i:], m.Heat)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Heat)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCreateLahmacunResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateLahmacunResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateLahmacunResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgUpdateLahmacun) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateLahmacun) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateLahmacun) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Onion) > 0 {
		i -= len(m.Onion)
		copy(dAtA[i:], m.Onion)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Onion)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.Tomato) > 0 {
		i -= len(m.Tomato)
		copy(dAtA[i:], m.Tomato)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Tomato)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Meat) > 0 {
		i -= len(m.Meat)
		copy(dAtA[i:], m.Meat)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Meat)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Dough) > 0 {
		i -= len(m.Dough)
		copy(dAtA[i:], m.Dough)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Dough)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Heat) > 0 {
		i -= len(m.Heat)
		copy(dAtA[i:], m.Heat)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Heat)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateLahmacunResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateLahmacunResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateLahmacunResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgUpdateParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.Params.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgUpdateParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgCreateLahmacun) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Heat)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Dough)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Meat)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Tomato)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Onion)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgCreateLahmacunResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgUpdateLahmacun) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Heat)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Dough)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Meat)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Tomato)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Onion)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgUpdateLahmacunResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgUpdateParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateLahmacun) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateLahmacun: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateLahmacun: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Heat", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Heat = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Dough", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Dough = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Meat", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Meat = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tomato", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Tomato = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Onion", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Onion = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateLahmacunResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateLahmacunResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateLahmacunResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateLahmacun) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateLahmacun: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateLahmacun: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Heat", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Heat = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Dough", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Dough = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Meat", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Meat = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tomato", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Tomato = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Onion", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Onion = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateLahmacunResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateLahmacunResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateLahmacunResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
