// Code generated by protoc-gen-go-pulsar. DO NOT EDIT.
package lahmacun

import (
	_ "cosmossdk.io/api/amino"
	_ "cosmossdk.io/api/cosmos/msg/v1"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	runtime "github.com/cosmos/cosmos-proto/runtime"
	_ "github.com/cosmos/gogoproto/gogoproto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoiface "google.golang.org/protobuf/runtime/protoiface"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	io "io"
	reflect "reflect"
	sync "sync"
)

var (
	md_Lahmacun         protoreflect.MessageDescriptor
	fd_Lahmacun_creator protoreflect.FieldDescriptor
	fd_Lahmacun_id      protoreflect.FieldDescriptor
	fd_Lahmacun_heat    protoreflect.FieldDescriptor
	fd_Lahmacun_dough   protoreflect.FieldDescriptor
	fd_Lahmacun_meat    protoreflect.FieldDescriptor
	fd_Lahmacun_tomato  protoreflect.FieldDescriptor
	fd_Lahmacun_onion   protoreflect.FieldDescriptor
)

func init() {
	file_bilge_lahmacun_lahmacun_proto_init()
	md_Lahmacun = File_bilge_lahmacun_lahmacun_proto.Messages().ByName("Lahmacun")
	fd_Lahmacun_creator = md_Lahmacun.Fields().ByName("creator")
	fd_Lahmacun_id = md_Lahmacun.Fields().ByName("id")
	fd_Lahmacun_heat = md_Lahmacun.Fields().ByName("heat")
	fd_Lahmacun_dough = md_Lahmacun.Fields().ByName("dough")
	fd_Lahmacun_meat = md_Lahmacun.Fields().ByName("meat")
	fd_Lahmacun_tomato = md_Lahmacun.Fields().ByName("tomato")
	fd_Lahmacun_onion = md_Lahmacun.Fields().ByName("onion")
}

var _ protoreflect.Message = (*fastReflection_Lahmacun)(nil)

type fastReflection_Lahmacun Lahmacun

func (x *Lahmacun) ProtoReflect() protoreflect.Message {
	return (*fastReflection_Lahmacun)(x)
}

func (x *Lahmacun) slowProtoReflect() protoreflect.Message {
	mi := &file_bilge_lahmacun_lahmacun_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_Lahmacun_messageType fastReflection_Lahmacun_messageType
var _ protoreflect.MessageType = fastReflection_Lahmacun_messageType{}

type fastReflection_Lahmacun_messageType struct{}

func (x fastReflection_Lahmacun_messageType) Zero() protoreflect.Message {
	return (*fastReflection_Lahmacun)(nil)
}
func (x fastReflection_Lahmacun_messageType) New() protoreflect.Message {
	return new(fastReflection_Lahmacun)
}
func (x fastReflection_Lahmacun_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_Lahmacun
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_Lahmacun) Descriptor() protoreflect.MessageDescriptor {
	return md_Lahmacun
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_Lahmacun) Type() protoreflect.MessageType {
	return _fastReflection_Lahmacun_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_Lahmacun) New() protoreflect.Message {
	return new(fastReflection_Lahmacun)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_Lahmacun) Interface() protoreflect.ProtoMessage {
	return (*Lahmacun)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_Lahmacun) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if x.Creator != "" {
		value := protoreflect.ValueOfString(x.Creator)
		if !f(fd_Lahmacun_creator, value) {
			return
		}
	}
	if x.Id != "" {
		value := protoreflect.ValueOfString(x.Id)
		if !f(fd_Lahmacun_id, value) {
			return
		}
	}
	if x.Heat != "" {
		value := protoreflect.ValueOfString(x.Heat)
		if !f(fd_Lahmacun_heat, value) {
			return
		}
	}
	if x.Dough != "" {
		value := protoreflect.ValueOfString(x.Dough)
		if !f(fd_Lahmacun_dough, value) {
			return
		}
	}
	if x.Meat != "" {
		value := protoreflect.ValueOfString(x.Meat)
		if !f(fd_Lahmacun_meat, value) {
			return
		}
	}
	if x.Tomato != "" {
		value := protoreflect.ValueOfString(x.Tomato)
		if !f(fd_Lahmacun_tomato, value) {
			return
		}
	}
	if x.Onion != "" {
		value := protoreflect.ValueOfString(x.Onion)
		if !f(fd_Lahmacun_onion, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_Lahmacun) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "bilge.lahmacun.Lahmacun.creator":
		return x.Creator != ""
	case "bilge.lahmacun.Lahmacun.id":
		return x.Id != ""
	case "bilge.lahmacun.Lahmacun.heat":
		return x.Heat != ""
	case "bilge.lahmacun.Lahmacun.dough":
		return x.Dough != ""
	case "bilge.lahmacun.Lahmacun.meat":
		return x.Meat != ""
	case "bilge.lahmacun.Lahmacun.tomato":
		return x.Tomato != ""
	case "bilge.lahmacun.Lahmacun.onion":
		return x.Onion != ""
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: bilge.lahmacun.Lahmacun"))
		}
		panic(fmt.Errorf("message bilge.lahmacun.Lahmacun does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Lahmacun) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "bilge.lahmacun.Lahmacun.creator":
		x.Creator = ""
	case "bilge.lahmacun.Lahmacun.id":
		x.Id = ""
	case "bilge.lahmacun.Lahmacun.heat":
		x.Heat = ""
	case "bilge.lahmacun.Lahmacun.dough":
		x.Dough = ""
	case "bilge.lahmacun.Lahmacun.meat":
		x.Meat = ""
	case "bilge.lahmacun.Lahmacun.tomato":
		x.Tomato = ""
	case "bilge.lahmacun.Lahmacun.onion":
		x.Onion = ""
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: bilge.lahmacun.Lahmacun"))
		}
		panic(fmt.Errorf("message bilge.lahmacun.Lahmacun does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_Lahmacun) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "bilge.lahmacun.Lahmacun.creator":
		value := x.Creator
		return protoreflect.ValueOfString(value)
	case "bilge.lahmacun.Lahmacun.id":
		value := x.Id
		return protoreflect.ValueOfString(value)
	case "bilge.lahmacun.Lahmacun.heat":
		value := x.Heat
		return protoreflect.ValueOfString(value)
	case "bilge.lahmacun.Lahmacun.dough":
		value := x.Dough
		return protoreflect.ValueOfString(value)
	case "bilge.lahmacun.Lahmacun.meat":
		value := x.Meat
		return protoreflect.ValueOfString(value)
	case "bilge.lahmacun.Lahmacun.tomato":
		value := x.Tomato
		return protoreflect.ValueOfString(value)
	case "bilge.lahmacun.Lahmacun.onion":
		value := x.Onion
		return protoreflect.ValueOfString(value)
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: bilge.lahmacun.Lahmacun"))
		}
		panic(fmt.Errorf("message bilge.lahmacun.Lahmacun does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Lahmacun) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "bilge.lahmacun.Lahmacun.creator":
		x.Creator = value.Interface().(string)
	case "bilge.lahmacun.Lahmacun.id":
		x.Id = value.Interface().(string)
	case "bilge.lahmacun.Lahmacun.heat":
		x.Heat = value.Interface().(string)
	case "bilge.lahmacun.Lahmacun.dough":
		x.Dough = value.Interface().(string)
	case "bilge.lahmacun.Lahmacun.meat":
		x.Meat = value.Interface().(string)
	case "bilge.lahmacun.Lahmacun.tomato":
		x.Tomato = value.Interface().(string)
	case "bilge.lahmacun.Lahmacun.onion":
		x.Onion = value.Interface().(string)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: bilge.lahmacun.Lahmacun"))
		}
		panic(fmt.Errorf("message bilge.lahmacun.Lahmacun does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Lahmacun) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "bilge.lahmacun.Lahmacun.creator":
		panic(fmt.Errorf("field creator of message bilge.lahmacun.Lahmacun is not mutable"))
	case "bilge.lahmacun.Lahmacun.id":
		panic(fmt.Errorf("field id of message bilge.lahmacun.Lahmacun is not mutable"))
	case "bilge.lahmacun.Lahmacun.heat":
		panic(fmt.Errorf("field heat of message bilge.lahmacun.Lahmacun is not mutable"))
	case "bilge.lahmacun.Lahmacun.dough":
		panic(fmt.Errorf("field dough of message bilge.lahmacun.Lahmacun is not mutable"))
	case "bilge.lahmacun.Lahmacun.meat":
		panic(fmt.Errorf("field meat of message bilge.lahmacun.Lahmacun is not mutable"))
	case "bilge.lahmacun.Lahmacun.tomato":
		panic(fmt.Errorf("field tomato of message bilge.lahmacun.Lahmacun is not mutable"))
	case "bilge.lahmacun.Lahmacun.onion":
		panic(fmt.Errorf("field onion of message bilge.lahmacun.Lahmacun is not mutable"))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: bilge.lahmacun.Lahmacun"))
		}
		panic(fmt.Errorf("message bilge.lahmacun.Lahmacun does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_Lahmacun) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "bilge.lahmacun.Lahmacun.creator":
		return protoreflect.ValueOfString("")
	case "bilge.lahmacun.Lahmacun.id":
		return protoreflect.ValueOfString("")
	case "bilge.lahmacun.Lahmacun.heat":
		return protoreflect.ValueOfString("")
	case "bilge.lahmacun.Lahmacun.dough":
		return protoreflect.ValueOfString("")
	case "bilge.lahmacun.Lahmacun.meat":
		return protoreflect.ValueOfString("")
	case "bilge.lahmacun.Lahmacun.tomato":
		return protoreflect.ValueOfString("")
	case "bilge.lahmacun.Lahmacun.onion":
		return protoreflect.ValueOfString("")
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: bilge.lahmacun.Lahmacun"))
		}
		panic(fmt.Errorf("message bilge.lahmacun.Lahmacun does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_Lahmacun) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in bilge.lahmacun.Lahmacun", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_Lahmacun) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Lahmacun) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_Lahmacun) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_Lahmacun) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*Lahmacun)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		l = len(x.Creator)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.Id)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.Heat)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.Dough)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.Meat)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.Tomato)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.Onion)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*Lahmacun)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if len(x.Onion) > 0 {
			i -= len(x.Onion)
			copy(dAtA[i:], x.Onion)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Onion)))
			i--
			dAtA[i] = 0x3a
		}
		if len(x.Tomato) > 0 {
			i -= len(x.Tomato)
			copy(dAtA[i:], x.Tomato)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Tomato)))
			i--
			dAtA[i] = 0x32
		}
		if len(x.Meat) > 0 {
			i -= len(x.Meat)
			copy(dAtA[i:], x.Meat)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Meat)))
			i--
			dAtA[i] = 0x2a
		}
		if len(x.Dough) > 0 {
			i -= len(x.Dough)
			copy(dAtA[i:], x.Dough)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Dough)))
			i--
			dAtA[i] = 0x22
		}
		if len(x.Heat) > 0 {
			i -= len(x.Heat)
			copy(dAtA[i:], x.Heat)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Heat)))
			i--
			dAtA[i] = 0x1a
		}
		if len(x.Id) > 0 {
			i -= len(x.Id)
			copy(dAtA[i:], x.Id)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Id)))
			i--
			dAtA[i] = 0x12
		}
		if len(x.Creator) > 0 {
			i -= len(x.Creator)
			copy(dAtA[i:], x.Creator)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Creator)))
			i--
			dAtA[i] = 0xa
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*Lahmacun)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: Lahmacun: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: Lahmacun: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Creator = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 2:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Id = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 3:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Heat", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Heat = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 4:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Dough", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Dough = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 5:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Meat", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Meat = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 6:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Tomato", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Tomato = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 7:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Onion", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Onion = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.0
// 	protoc        (unknown)
// source: bilge/lahmacun/lahmacun.proto

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SpiceLevel int32

const (
	SpiceLevel_MILD   SpiceLevel = 0
	SpiceLevel_MEDIUM SpiceLevel = 1
	SpiceLevel_HOT    SpiceLevel = 2
)

// Enum value maps for SpiceLevel.
var (
	SpiceLevel_name = map[int32]string{
		0: "MILD",
		1: "MEDIUM",
		2: "HOT",
	}
	SpiceLevel_value = map[string]int32{
		"MILD":   0,
		"MEDIUM": 1,
		"HOT":    2,
	}
)

func (x SpiceLevel) Enum() *SpiceLevel {
	p := new(SpiceLevel)
	*p = x
	return p
}

func (x SpiceLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SpiceLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_bilge_lahmacun_lahmacun_proto_enumTypes[0].Descriptor()
}

func (SpiceLevel) Type() protoreflect.EnumType {
	return &file_bilge_lahmacun_lahmacun_proto_enumTypes[0]
}

func (x SpiceLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SpiceLevel.Descriptor instead.
func (SpiceLevel) EnumDescriptor() ([]byte, []int) {
	return file_bilge_lahmacun_lahmacun_proto_rawDescGZIP(), []int{0}
}

type Lahmacun struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Id      string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Heat    string `protobuf:"bytes,3,opt,name=heat,proto3" json:"heat,omitempty"`
	Dough   string `protobuf:"bytes,4,opt,name=dough,proto3" json:"dough,omitempty"`
	Meat    string `protobuf:"bytes,5,opt,name=meat,proto3" json:"meat,omitempty"`
	Tomato  string `protobuf:"bytes,6,opt,name=tomato,proto3" json:"tomato,omitempty"`
	Onion   string `protobuf:"bytes,7,opt,name=onion,proto3" json:"onion,omitempty"`
}

func (x *Lahmacun) Reset() {
	*x = Lahmacun{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilge_lahmacun_lahmacun_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Lahmacun) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lahmacun) ProtoMessage() {}

// Deprecated: Use Lahmacun.ProtoReflect.Descriptor instead.
func (*Lahmacun) Descriptor() ([]byte, []int) {
	return file_bilge_lahmacun_lahmacun_proto_rawDescGZIP(), []int{0}
}

func (x *Lahmacun) GetCreator() string {
	if x != nil {
		return x.Creator
	}
	return ""
}

func (x *Lahmacun) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Lahmacun) GetHeat() string {
	if x != nil {
		return x.Heat
	}
	return ""
}

func (x *Lahmacun) GetDough() string {
	if x != nil {
		return x.Dough
	}
	return ""
}

func (x *Lahmacun) GetMeat() string {
	if x != nil {
		return x.Meat
	}
	return ""
}

func (x *Lahmacun) GetTomato() string {
	if x != nil {
		return x.Tomato
	}
	return ""
}

func (x *Lahmacun) GetOnion() string {
	if x != nil {
		return x.Onion
	}
	return ""
}

var File_bilge_lahmacun_lahmacun_proto protoreflect.FileDescriptor

var file_bilge_lahmacun_lahmacun_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x62, 0x69, 0x6c, 0x67, 0x65, 0x2f, 0x6c, 0x61, 0x68, 0x6d, 0x61, 0x63, 0x75, 0x6e,
	0x2f, 0x6c, 0x61, 0x68, 0x6d, 0x61, 0x63, 0x75, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0e, 0x62, 0x69, 0x6c, 0x67, 0x65, 0x2e, 0x6c, 0x61, 0x68, 0x6d, 0x61, 0x63, 0x75, 0x6e, 0x1a,
	0x11, 0x61, 0x6d, 0x69, 0x6e, 0x6f, 0x2f, 0x61, 0x6d, 0x69, 0x6e, 0x6f, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x17, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x2f, 0x6d, 0x73, 0x67, 0x2f, 0x76,
	0x31, 0x2f, 0x6d, 0x73, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x19, 0x63, 0x6f, 0x73,
	0x6d, 0x6f, 0x73, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x14, 0x67, 0x6f, 0x67, 0x6f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x67, 0x6f, 0x67, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x62, 0x69,
	0x6c, 0x67, 0x65, 0x2f, 0x6c, 0x61, 0x68, 0x6d, 0x61, 0x63, 0x75, 0x6e, 0x2f, 0x70, 0x61, 0x72,
	0x61, 0x6d, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa0, 0x01, 0x0a, 0x08, 0x4c, 0x61,
	0x68, 0x6d, 0x61, 0x63, 0x75, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x68, 0x65, 0x61, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x68, 0x65, 0x61, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x64, 0x6f, 0x75, 0x67, 0x68, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x64, 0x6f, 0x75, 0x67, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x65,
	0x61, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6d, 0x65, 0x61, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x74, 0x6f, 0x6d, 0x61, 0x74, 0x6f, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x74, 0x6f, 0x6d, 0x61, 0x74, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x6e, 0x69, 0x6f, 0x6e, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6f, 0x6e, 0x69, 0x6f, 0x6e, 0x2a, 0x2b, 0x0a, 0x0a,
	0x53, 0x70, 0x69, 0x63, 0x65, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x08, 0x0a, 0x04, 0x4d, 0x49,
	0x4c, 0x44, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x4d, 0x45, 0x44, 0x49, 0x55, 0x4d, 0x10, 0x01,
	0x12, 0x07, 0x0a, 0x03, 0x48, 0x4f, 0x54, 0x10, 0x02, 0x42, 0x96, 0x01, 0x0a, 0x12, 0x63, 0x6f,
	0x6d, 0x2e, 0x62, 0x69, 0x6c, 0x67, 0x65, 0x2e, 0x6c, 0x61, 0x68, 0x6d, 0x61, 0x63, 0x75, 0x6e,
	0x42, 0x0d, 0x4c, 0x61, 0x68, 0x6d, 0x61, 0x63, 0x75, 0x6e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50,
	0x01, 0x5a, 0x18, 0x62, 0x69, 0x6c, 0x67, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x62, 0x69, 0x6c,
	0x67, 0x65, 0x2f, 0x6c, 0x61, 0x68, 0x6d, 0x61, 0x63, 0x75, 0x6e, 0xa2, 0x02, 0x03, 0x42, 0x4c,
	0x58, 0xaa, 0x02, 0x0e, 0x42, 0x69, 0x6c, 0x67, 0x65, 0x2e, 0x4c, 0x61, 0x68, 0x6d, 0x61, 0x63,
	0x75, 0x6e, 0xca, 0x02, 0x0e, 0x42, 0x69, 0x6c, 0x67, 0x65, 0x5c, 0x4c, 0x61, 0x68, 0x6d, 0x61,
	0x63, 0x75, 0x6e, 0xe2, 0x02, 0x1a, 0x42, 0x69, 0x6c, 0x67, 0x65, 0x5c, 0x4c, 0x61, 0x68, 0x6d,
	0x61, 0x63, 0x75, 0x6e, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61,
	0xea, 0x02, 0x0f, 0x42, 0x69, 0x6c, 0x67, 0x65, 0x3a, 0x3a, 0x4c, 0x61, 0x68, 0x6d, 0x61, 0x63,
	0x75, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_bilge_lahmacun_lahmacun_proto_rawDescOnce sync.Once
	file_bilge_lahmacun_lahmacun_proto_rawDescData = file_bilge_lahmacun_lahmacun_proto_rawDesc
)

func file_bilge_lahmacun_lahmacun_proto_rawDescGZIP() []byte {
	file_bilge_lahmacun_lahmacun_proto_rawDescOnce.Do(func() {
		file_bilge_lahmacun_lahmacun_proto_rawDescData = protoimpl.X.CompressGZIP(file_bilge_lahmacun_lahmacun_proto_rawDescData)
	})
	return file_bilge_lahmacun_lahmacun_proto_rawDescData
}

var file_bilge_lahmacun_lahmacun_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_bilge_lahmacun_lahmacun_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_bilge_lahmacun_lahmacun_proto_goTypes = []interface{}{
	(SpiceLevel)(0),  // 0: bilge.lahmacun.SpiceLevel
	(*Lahmacun)(nil), // 1: bilge.lahmacun.Lahmacun
}
var file_bilge_lahmacun_lahmacun_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_bilge_lahmacun_lahmacun_proto_init() }
func file_bilge_lahmacun_lahmacun_proto_init() {
	if File_bilge_lahmacun_lahmacun_proto != nil {
		return
	}
	file_bilge_lahmacun_params_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_bilge_lahmacun_lahmacun_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Lahmacun); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bilge_lahmacun_lahmacun_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bilge_lahmacun_lahmacun_proto_goTypes,
		DependencyIndexes: file_bilge_lahmacun_lahmacun_proto_depIdxs,
		EnumInfos:         file_bilge_lahmacun_lahmacun_proto_enumTypes,
		MessageInfos:      file_bilge_lahmacun_lahmacun_proto_msgTypes,
	}.Build()
	File_bilge_lahmacun_lahmacun_proto = out.File
	file_bilge_lahmacun_lahmacun_proto_rawDesc = nil
	file_bilge_lahmacun_lahmacun_proto_goTypes = nil
	file_bilge_lahmacun_lahmacun_proto_depIdxs = nil
}
